---
- name: Ensure that the postfix packages are installed
  tags: postfix
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: postfix_yum
  loop:
    - postfix
    - "{{ postfix_packages }}"

- name: Attempting to fetch postfix version from RPM database
  tags: postfix
  check_mode: false
  args:
    warn: no
  command: |
    rpm -q --queryformat %{version} postfix
  register: postfix_rpm
  changed_when: false

- name: Attempting to set postfix_version fact
  tags: postfix
  set_fact:
    postfix_version: "{{ postfix_rpm.stdout }}"
  when:
    - postfix_rpm is not skipped
    - postfix_rpm is success

- name: Attempting to overlay postfix configurations
  tags: postfix
  become: true
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  register: postfix_template
  notify: restart postfix

- name: Attempting to overlay postfix generic maps, if applicable
  tags: postfix
  become: true
  template:
    src: generic.j2
    dest: /etc/postfix/generic
    owner: root
    group: root
    mode: 0600
  notify: postmap generic
  when: postfix_parameters.smtp_generic_maps is defined

- name: Attempting to overlay postfix sasl password maps, if applicable
  tags: postfix
  become: true
  no_log: true
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: 0600
  notify: postmap sasl_passwd
  when:
    - postfix_parameters.relayhost is defined
    - postfix_parameters.smtp_sasl_password_maps is defined
    - postfix_sasl_password is defined
    - postfix_sasl_username is defined

- name: Attempting to overlay postfix sender canonical regular expressions, if applicable
  tags: postfix
  become: true
  template:
    src: sender_canonical.j2
    dest: /etc/postfix/sender_canonical
    owner: root
    group: root
    mode: 0600
  when: postfix_parameters.sender_canonical is defined

- name: Ensure that postfix is started and enabled on boot
  tags: postfix
  become: true
  service:
    enabled: yes
    name: postfix
    state: started
  when:
    - postfix_template is success
    - postfix_yum is success
...
